/beamformphase:
    ros__parameters:
        verbose: true
        initial_angle: 0.0

        #reference
        #number_of_microphones: 3
        #mic0: [0.000, 0.000]
        #mic1: [0.000, 0.000]
        #mic2: [0.000, 0.000]

        #aira3 clean
        number_of_microphones: 3
        mic0: [ 0.000,  0.000]
        mic1: [ 0.000, -0.180]
        mic2: [-0.156, -0.090]

        #aira3 noisy
        #number_of_microphones: 3
        #mic0: [ 0.000,  0.000]
        #mic1: [ 0.000, -0.210]
        #mic2: [-0.182, -0.105]

        #aira16 first 3 microphones
        #number_of_microphones: 3
        #mic0:  [ 0.158,  0.115]
        #mic1:  [ 0.158, -0.115]
        #mic2:  [-0.045,  0.000]

        #aira16 first 6 microphones
        #number_of_microphones: 6
        #mic0:  [ 0.158,  0.115]
        #mic1:  [ 0.158, -0.115]
        #mic2:  [-0.045,  0.000]
        #mic3:  [-0.050, -0.188]
        #mic4:  [-0.195,  0.000]
        #mic5:  [-0.057,  0.186]

        #test bench
        #number_of_microphones: 3
        #mic0: [ 0.000,  0.000]
        #mic1: [ 0.000, -0.215]
        #mic2: [-0.160, -0.1075]

        #8soundusbcarboard
        #number_of_microphones: 3
        #mic0: [ 0.000,  0.000]
        #mic1: [ 0.000, -0.210]
        #mic2: [-0.181, -0.105]

        #2mictest
        #number_of_microphones: 2
        #mic0: [ 0.000,  0.000]
        #mic1: [ 0.000, -0.210]

        #aira16
        #number_of_microphones: 16
        #mic0:  [ 0.158,  0.115,  0.000]
        #mic1:  [ 0.158, -0.115,  0.000]
        #mic2:  [-0.045,  0.000,  0.000]
        #mic3:  [-0.050, -0.188,  0.000]
        #mic4:  [-0.195,  0.000,  0.000]
        #mic5:  [-0.057,  0.186,  0.000]
        #mic6:  [ 0.180,  0.000, -0.168]
        #mic7:  [ 0.158, -0.115, -0.335]
        #mic8:  [ 0.056, -0.171, -0.168]
        #mic9:  [-0.050, -0.188, -0.335]
        #mic10: [-0.128, -0.098, -0.168]
        #mic11: [-0.195,  0.000, -0.335]
        #mic12: [-0.132,  0.098, -0.168]
        #mic13: [-0.057,  0.186, -0.335]
        #mic14: [ 0.056,  0.171, -0.168]
        #mic15: [ 0.158,  0.115, -0.335]

        #aira16-binaural (15,9) -1 = (14,8)
        #number_of_microphones: 2
        #mic0: [ 0.000,  0.000]
        #mic1: [ 0.000, -0.342]

