/masacoord:
    ros__parameters:
        ReadMicWavs_dir: /home/balkce/masa/src/ReadMicWavs
        input_length: 0.512
        init_doa: 15.0
        eta: 0.3
        smooth_weight: 0.9
        quality_type: 'stoi' # can be: 'sdr', 'stoi, or 'pesq'
        wait_for_qual: 1.5
        max_time: 120.0
        masa_order: [
          'beamformer',
          'demucs',
          'jack_write',
          'online_sqa',
          'ReadMicWavs',
          'soundloc',
          'doaoptimizer',
          'theta_plot',
          'doa_plot',
          'qual_plot',
        ]

